### ISSUE TITLE
CC and BCC for MIME types

### ISSUE THREAD

**Issue by sadeqzadeh** [1lobby/mailgun-js#65] opened 2015-05-23 20:25 UTC
It seems that it is not possible to have CC and BCC in an email with HTML body, for example, since you have to explicitly set "to" field after mailComposer builds the message:

```
mailComposer.buildMessage(function(mailBuildError, messageSource) {
    var dataToSend = {
      to: recipients[0],
      message: messageSource
    };

    mgSender.messages().sendMime(dataToSend, function (error, response) {
    ...
```

**Comment by sadeqzadeh** [comment] 2015-05-23 20:37
[This] (http://blog.mailgun.com/mailgun-api-2-0-forget-mime/) might help other users.

**Comment by sadeqzadeh** [comment] 2015-05-23 23:49
Here is how I did it using `request`:

```
function sendEmail(event, content) {
  if (!process.env.MAILGUN_API_KEY) {
    winston.error('Mailgun API key must be set as an environment variable');
  }

  var noReplyAddr = '<noreply@mycompany.com>';
  var form = {
    from: 'Company Name ' + noReplyAddr,
    to: recipients[0],
    subject: 'my subject',
    text: text,
    html: html
  };
  if (recipients.length > 1) {
    form.bcc = recipients.slice(1);
  }

  var deferred = Q.defer();

  function callback(error, response) {
    if (error) {
      console.log("Mailgun ERROR:", error);
      deferred.reject(error);
    } else {
      console.log("Mailgun SUCCESS.");
      deferred.resolve(response);
    }
  }

  request.post({
        url: myMailgunUrl,
        form: httpForm
      },callback)
      .auth('api', process.env.MAILGUN_API_KEY, false);

  return deferred.promise;
}
```

**Comment by bojand** [comment] 2015-06-03 15:35
Hello, I am not sure I understand completely. In first comment you're sending to mime endpoint, in the comment above you seem to be sending to the normal api endpoint (I think)? This worked fine for me:

```
var params = {
  to: 'mygmailemail@gmail.com',
  bcc: 'mycompanyemail@mycompany.com',
  from: 'myoutlookemail@outlook.com',
  subject: 'testing stuff again',
  text: 'testing message for mailgun',
  html: 'HTML version of body'
};

mailgun.messages().send(params, function (err, body) {
  if (err) console.dir(err);
});
```

**Comment by sadeqzadeh** [comment] 2015-06-04 08:00
When you deal with Mailgun's HTTP API, you don't need to worry about mime type, as those are handled by Mailgun's backend. You can see from my httpForm that I have a HTML attribute (which is not possible without having mime type set properly). You can have attachments and other stuff as well, and Mailgun server composes and handles mime type properly.

**Comment by bojand** [comment] 2015-06-23 00:59
I am still not sure what's the issue here. Multiple examples were given without full explanation that I understand on what exactly the issue is or how to reproduce it. I have shown working sample code that does exactly what I understood the issue is. Also the library has been updated to version 3 of the Mailgun API. Without a reproducible sample source code that demonstrates the problem I am not sure what I can do. Closing due to lack of clarification, activity and clear sample source. I am free to reopening if more information is given.

**Closed by bojand** 2015-06-23 00:59 UTC

**Comment by fabyeah** [comment] 2015-10-27 16:56
@bojand This should be reopened. I have the same problem, You HAVE to set the 'to' field or no emails will be sent. But I ONLY want to send BCC emails! What do I do here, except looping the send function? 
Additionally defining all recipients in 'to' as explained in #9 doesn't work for me either.

**Comment by bojand** [comment] 2015-10-27 17:33
Please try the latest release: 0.7.4. If that doesn't work, please explain exactly the issue, add sample source code to reproduce it and demonstrate the problem. Please see my last comment in the thread. Without sample code and an actual identifiable bug there is little I can do.

**Comment by Christilut** [comment] 2018-03-20 14:02
For those still running into this (like I just did):

As per the [Mailgun documentation](https://documentation.mailgun.com/en/latest/api-sending.html#sending), you have to add the BCC addresses to the TO addresses. However Mailgun will remove them from the TO address list and your BCC recipients will not see any other BCC addresses.

If you use mailcomposer, make sure you don't add the BCC field because then your BCC recipients will see all addresses.

**Comment by holdenweb** [comment] 2018-08-10 09:33
It seems possible some users might have made the mistake of assuming that mail channels use the recipients in the message headers - they don't. Routing information is handled entirely separately from the message content (headers and body).

The recipient(s) of an email do not need to be named in the message headers at all, though it is conventional to do so. If they did the Bcc feature could never work, since the addresses would have to be part of the message and so wouldn't be hidden! Particularly in the case of spam, recipients and senders in message headers can differ from the addresses used to for routing. Thats why the latter have to be supplied to the API request as separate parameters, rather than being implied from the message content.
